services:

  main:
    restart: always
    build: .
    container_name: ${APPNAME}_main
    environment:
      - DEBUG=true
      - REDIS_SERVICE=redis
      - APPNAME=${APPNAME}
    command: ./start-server.sh python manage.py runserver 0.0.0.0:8000

volumes:
  pgdata:
  redisdata:
  solrdata: