pythonpath = '/app'
workers = 2
timeout = 30
worker_class = 'gevent'
max_requests = 1000
loglevel = 'info'
bind = "0.0.0.0:8000"
errorlog = '-'
accesslog = '-'
# access_log_format = '%(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"'
access_log_format = '%({x-forwarded-for}i)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"'