---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{project_name}}-celery
  labels:
    tier: backend
    project: {{project_name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: {{project_name}}-django-pod
      project: {{project_name}}
  template:
    metadata:
      annotations:
        sidecar.istio.io/proxyCPU: "10m"
        sidecar.istio.io/proxyMemory: "50Mi"
      labels:
        pod: celery-django-pod
        tier: backend
        project: {{project_name}}
    spec:
#      imagePullSecrets:
#        - name:
#      nodeSelector:
#        doks.digitalocean.com/node-pool: ..
      containers:
      - name: {{project_name}}-celery
#        image: ..
        env:
          - name: DB_SERVICE
            value: postgres-svc-headless
          - name: DB_PORT
            value: "5432"
          - name: PGB_SERVICE
            value: pgbouncer-svc-node
          - name: PGB_PORT
            value: "6432"
          - name: REDIS_SERVICE
            value: redis-svc-headless
          - name: SOLR_SERVICE
            value: unset
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{project_name}}-redis
                key: redis-password
          - name: SENTRY_ENV
            value: production
#          - name: SENTRY_DSN
#            value: ..
        envFrom:
        - configMapRef:
            name: {{project_name}}-env-config
        imagePullPolicy: Always
        args: ["celery", "-A", "{{project_name}}", "worker"]
