services:
  main:
    restart: unless-stopped
    ports:
      - "8000:8000"
    build:
      context: ..
      args:
        - DEBUG=true
    volumes:
    - ./media:/app/media
    - ./db.sqlite3:/app/db.sqlite3
